### ISSUE TITLE
appID or appName for Evaluation.scala

### ISSUE THREAD

**Issue by kithokit** [PredictionIO/template-scala-parallel-classification#4]
I am trying your new feature on evaluation based on https://docs.prediction.io/evaluation/paramtuning/

It is asking to use appID instead of appName. But the lastest version of this from github is using AppName.

![screen shot 2015-05-22 at 11 31 52 am](https://cloud.githubusercontent.com/assets/920483/7763622/57776578-0076-11e5-9df7-92ca7690cf1d.png)

I can't run the evaluation successfully.

```
Spark assembly has been built with Hive, including Datanucleus jars on classpath
[INFO] [CoreWorkflow$] runEvaluation started
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@c3aa85f87942:51580]
[INFO] [CoreWorkflow$] Starting evaluation instance ID: AU15dIgWjNmwxoliJhCz
[INFO] [Engine$] DataSource: org.template.classification.DataSource@4a9860
[INFO] [Engine$] Preparator: org.template.classification.Preparator@4ac8768e
[INFO] [Engine$] AlgorithmList: List(org.template.classification.NaiveBayesAlgorithm@3db432c2)
[INFO] [Engine$] Serving: org.template.classification.Serving@4041739c
[ERROR] [Common$] Invalid app name INVALID_APP_NAME
Exception in thread "main" java.lang.IllegalArgumentException: Invalid app name INVALID_APP_NAME
	at io.prediction.data.store.Common$$anonfun$appNameToId$2.apply(Common.scala:47)
	at io.prediction.data.store.Common$$anonfun$appNameToId$2.apply(Common.scala:45)
	at scala.Option.getOrElse(Option.scala:120)
	at io.prediction.data.store.Common$.appNameToId(Common.scala:45)
```

**Comment by tom-chan** [comment]
Can you check if you get the appName right? "pio app list" shows the mapping between appId and appName.

**Comment by kithokit** [comment]
The latest version of template Classification is showing appName. But the docs said should use appId

**Comment by k4hoo** [comment]
the doc seems outdated. should be appName. would be great if you help us fix the doc! thanks! :)
You need to change the param in this line to point to your app name.
https://github.com/PredictionIO/template-scala-parallel-classification/blob/v0.3.0/src/main/scala/Evaluation.scala#L27

**Comment by mzjgithub** [comment]
[ERROR] [Common$] Invalid app name INVALID_APP_NAME
======engine.json  file=======================
"appName": "INVALID_APP_NAME"
Change "INVALID_APP_NAME" to appName of your

**Comment by zfengli89** [comment]
please run command ‘pio build’ again
